### ISSUE TITLE
handling multiple relations for the same concept sets

### ISSUE THREAD

**Issue by Schweikhard** [concepticon/pyconcepticon#11]
As came up during the integrations of new conceptrelations, the current version of concepticon test cannot handle concepts having more than one relation.

The dictionary there currently as the structure:

{
   "concept1": {
        "concept2": "relation-unique"
   }
}

We'll probably need a set/list there:

{
   "concept1": {
        "concept2": ["relation-A", "relation-B"]
   }
}

**Comment by xrotwang** [comment]
See    https://github.com/concepticon/pyconcepticon/blob/55a490a8bae20807c25acca000a1fdd09d15a39c/src/pyconcepticon/api.py#L174-L179
