### ISSUE TITLE
Integrate cldfcatalog

### ISSUE THREAD

**Issue by xrotwang** [concepticon/pyconcepticon#15]
Based on `cldfcatalog`, discovering the location of `concepticon-data` should be simplified.
Here's how this could look like in `pyclts`: https://github.com/cldf-clts/pyclts#install

**Comment by xrotwang** [comment]
@LinguList this should already make things somewhat more stable. What do you think?

**Comment by xrotwang** [comment]
This doesn't mention the versioning integration yet, but that's implemented for pyclts as well:
```
$ clts -h
usage: clts [-h] [--log-level LOG_LEVEL] [--repos REPOS]
            [--repos-version REPOS_VERSION] [--system SYSTEM]
            COMMAND ...

optional arguments:
  -h, --help            show this help message and exit
  --log-level LOG_LEVEL
                        log level [ERROR|WARN|INFO|DEBUG] (default: 20)
  --repos REPOS         clone of cldf-clts/clts (default:
                        /home/forkel/.config/cldf/clts)
  --repos-version REPOS_VERSION
                        version of repository data. Requires a git clone!
                        (default: None)
```

**Comment by LinguList** [comment]
Yes, I guess this will help a lot. 

BTW: we also have (as a potential future catalog) [orthograpy](https://github.com/cldf/orthograpy). I think, the logic of separating data and code should in this case apply there as well, provided we decide at some point to really push and publish it...
