### ISSUE TITLE
make_app doesn't have args.args from Concepticon.app_wrapper

### ISSUE THREAD

**Issue by chrzyki** [concepticon/pyconcepticon#17]
Calling `concepticon make_app` ...

https://github.com/concepticon/pyconcepticon/blob/9d1c1c4295bed703776ed7bc2c55fad5893a98f9/src/pyconcepticon/commands/make_app.py#L14

makes us of the `app_wrapper` ...

https://github.com/clld/clldutils/blob/65ac0344526cdc9b12bd6910113331515d4bca61/src/clldutils/apilib.py#L97

which doesn't have `args.args` populated, as far as I can tell. Or am I misremembering how to use/call `make_app`?

**Comment by xrotwang** [comment]
ok, anything but a bugfix release of clldutils would be inappropriate, I guess.
