### ISSUE TITLE
make tests for authors 

### ISSUE THREAD

**Issue by LinguList** [concepticon/pyconcepticon#32]
Authors are bibtex-styled, so we expect: multiple authors split by " and ", and then we have `familyname, firstname` or `firstname familyname`. 

I assume, given that pybtex is also not strong in this regard, that we best add an `Author` class doing the parsing here? It should raise an error if there are multiple commas and no `and` or `AND`, for example. 

I am also fine with a regex in the attr.ib evaluation.

**Comment by SimonGreenhill** [comment]
Hmm, we have this information in two places -- the bibtex and the csv file. Do we need it in the csv at all ? Or a simple check would be 'does the string in the csv match the string in the bibtex'

**Comment by LinguList** [comment]
It is not that easy. The information *seems* duplicated, but it isn't, as you can see from [Yakhontov's lists](https://concepticon.clld.org/contributions/Yakhontov-1991-100): The author of the reference is Sergei Starostin, but he quotes PC with Yakhontov, so Yakhontov is the author of the list.

**Comment by SimonGreenhill** [comment]
Ahh, ok. I guess you could add these to the bibtex, so then then citekeys just need to go in the csv file?

**Comment by LinguList** [comment]
Nope, there is no real reference for Yakhontov as an author of that list, the reference and source is Starostin, making a fake reference feels bad. We had a longer discussion about this in the beginning of concepticon, and I pulled out quite a few of those examples where an author of a list is not the author of the reference in which the list occurs. It's less than 5% of what we have now, I admit, but I want to keep a "humanities" attitude towards referencing, and this seems quite the best way to me. I guess, a regex in the evaluation is trivial, and won't blow the code... (even less complicated than adding these to the references now).

**Comment by SimonGreenhill** [comment]
Ok :)

**Comment by xrotwang** [comment]
see #34
