### ISSUE TITLE
`test` command with a single list runs check on everything

### ISSUE THREAD

**Issue by SimonGreenhill** [concepticon/pyconcepticon#37]
Despite what it says in the help, `concepticon test xxx` does not just test list `xxx` but all the lists.

**Comment by SimonGreenhill** [comment]
Think it's this loop here not short-circuiting when given a clid: https://github.com/concepticon/pyconcepticon/blob/master/src/pyconcepticon/api.py#L428

**Comment by LinguList** [comment]
Yes, the test tests all, you should use `check` for an individual list, 
also to see the mergers.
