### ISSUE TITLE
path-issues

### ISSUE THREAD

**Issue by LinguList** [concepticon/pyconcepticon#4]
In my current installation, I have path issues: mapping only works when I reside inside the concepticon folder. Can or do we have the possibility to assign where the conceepticon-repos resides?

**Comment by xrotwang** [comment]
yes. See the [README](https://github.com/concepticon/pyconcepticon/blob/master/README.md#usage). The `Concepticon` object is initialized passing in the path to `concepticon-data`, the CLI takes a `--repos=PATH/TO/concepticon-data` option.
